name = "my name is alex"
name1 = "my name is {name1}"

print(name.capitalize())
print(name.count("a"))
print(name.casefold())
print(name.center(50,"-"))
print(name.endswith("ex"))
print(name[name.find("name"):8])
print(name1.format(name1 = "oliver"))
print(name1.format_map({'name1':'oliver'}))
print('ab23'.isalnum())
print('1A'.isalpha())
print('1'.isdigit())
print('a和我1A'.isidentifier()) #判断是否是一个合法的标识符
print('a 1A'.islower())
print('2233'.isnumeric())
print('My Name Is '.istitle())
print('My Name Is'.isprintable())
print('M'.isupper())
print('+'.join(['1','2','3','4']))
print(name.ljust(50,'*'))
print(name.rjust(50,'*'))
print('Alex'.lower())
print('alex'.upper())
print('\nAlex'.lstrip())
print('Alex\n'.rstrip())
print('    Alex\n'.strip())
p = str.maketrans("abcdef",'123456')

print("alex li".translate(p))

print('alex li'.replace('l','L',1))
print('alex li'.rfind('l'))
print('2+3+4+4'.split("+"))
print('1+2\n+3+4'.splitlines())
print('Alex Li'.swapcase())
print('Alex Li'.title())
print('Alex Li'.zfill(50))